### ISSUE TITLE
PHP failed to build - no such file or directory

### ISSUE THREAD

**Issue by alex-secondnature** [Daursu/laradocker#5]
Running fresh Laravel 7 install with `docker-compose up`.

```
ERROR: Service 'php' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder142423313/resources/assets: no such file or directory
```

Fixed by adding `resources/assets` dir.

Then:

```
error cross-env@7.0.2: The engine "node" is incompatible with this module. Expected version ">=10.14". Got "8.17.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.
ERROR: Service 'php' failed to build: The command '/bin/sh -c mkdir -p /app/public     && yarn install && yarn run production' returned a non-zero code: 1

```

**Comment by Daursu** [comment]
The error is due to the version of NodeJS used, as it's running Node 8 and Laravel Mix distributed with Laravel 7 and up require NodeJS >= 10.

I've update the repository, to use the latest versions NodeJS 12, PHP 7.4 and Nginx 1.19.

Also, I've created an example project based on Laravel 8 that works with docker-compose and ECS Fargate out of the box. You can find the code at https://github.com/daursu/docker-compose-laravel8

The documentation on https://www.laradocker.com has also been updated.
